table _measures
	lineageTag: 2821e051-91d3-41ac-8e1b-8b3ca1600053

	measure Listings = ```
			
			CALCULATE(
			    DISTINCTCOUNT(dim_listings[listing_id]),
			    dim_listings[listing_status] = "Activo"
			)
			
			```
		formatString: 0
		displayFolder: KPIs
		lineageTag: d184835a-bd11-4aba-8517-c8558336ac3a

	measure 'Precio de venta promedio' =
			
			CALCULATE(
			    AVERAGE(dim_listings[price]),
			    dim_listings[Tipo de operación] = "Venta"
			)
		displayFolder: KPIs
		lineageTag: 32ae598e-7ea0-4fab-8fa3-7d1170038b96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Leads = ```
			
			VAR _leads = COUNTROWS(fac_leads)
			VAR _result =
			        CALCULATE(
			            _leads,
			            USERELATIONSHIP(dim_dates[Fecha], fac_leads[lead_date])
			        )
			
			RETURN
			_result
			
			```
		formatString: 0
		displayFolder: KPIs
		lineageTag: 6c529afd-5f8f-42e0-813d-5e212a179de7

	measure 'Ratio Leads/Listings' = [Leads] / [Listings]
		formatString: 0.00
		displayFolder: KPIs
		lineageTag: 444ce03c-8aa2-480e-a6de-9cc3429c7bea

	measure Concretadas =
			
			CALCULATE(
			    COUNTROWS(dim_listings),
			    dim_listings[listing_status] = "Vendido"
			)
		formatString: 0
		displayFolder: KPIs
		lineageTag: e7bf869f-67ee-42f3-97d4-3d45e5e031d6

	measure _selected_dates =
			
			VAR FechaMin = FIRSTDATE(dim_dates[Fecha])
			VAR FechaMax = LASTDATE(dim_dates[Fecha])
			
			RETURN
			    "Fechas filtradas: "
			        & UNICHAR ( 10 ) & FechaMin & " - " & FechaMax
		isHidden
		displayFolder: _various
		lineageTag: 43775d8b-b70c-49bb-bc25-3481d3988b2f

		changedProperty = IsHidden

	column medidas
		dataType: string
		lineageTag: 5055c3b3-546b-4d2a-95b1-69c61ada5ae8
		summarizeBy: none
		sourceColumn: medidas

		annotation SummarizationSetBy = Automatic

	partition _measures = m
		mode: import
		source =
				let
				    Source = #table(
				        {"medidas"},
				        {
				            {"1"}
				        }
				    )
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

