table dim_customers
	lineageTag: 5cf43a08-853a-4479-8796-84fe685f9a91

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: da5f4e3b-deed-4e7e-b292-02c482b25106
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: ab174378-8644-4916-8cf5-96f500793a56
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column surname
		dataType: string
		lineageTag: b7586abe-0147-4741-8ed9-80345b1f776b
		summarizeBy: none
		sourceColumn: surname

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 06412584-00b5-4057-9683-cf85b548c2e2
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 1ce2f789-bd9e-4c1c-874b-e1fa3680dc50
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: ebf7d853-2325-4084-89ec-a7a2f2642069
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 7dfeb684-3d54-4009-91e8-b272dcffa03b
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column occupation
		dataType: string
		lineageTag: 71fa2b3a-c33d-4426-a882-56f99db3a98f
		summarizeBy: none
		sourceColumn: occupation

		annotation SummarizationSetBy = Automatic

	partition dim_customers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\luisa\OneDrive\Escritorio\real_state_analysis\real_state_source.xlsx"), null, true),
				    dim_customers_Sheet = Source{[Item="dim_customers",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(dim_customers_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"name", type text}, {"surname", type text}, {"country", type text}, {"city", type text}, {"age", Int64.Type}, {"gender", type text}, {"occupation", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

