table fac_listings
	lineageTag: 8fc82974-adc4-46ef-90dd-4c5b33730c35

	column listing_id
		dataType: int64
		formatString: 0
		lineageTag: ea2ed3dc-471c-412b-ad0a-ceb91347127f
		summarizeBy: none
		sourceColumn: listing_id

		annotation SummarizationSetBy = User

	column property_id
		dataType: int64
		formatString: 0
		lineageTag: de4e3bb0-e45e-446f-bbd5-475049cb5d5f
		summarizeBy: none
		sourceColumn: property_id

		annotation SummarizationSetBy = Automatic

	column publication_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 28fe879a-d468-4534-9b59-b4044bfac294
		summarizeBy: none
		sourceColumn: publication_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column price
		dataType: int64
		formatString: 0
		lineageTag: 08e1475d-7606-4231-b027-7f6b489baacd
		summarizeBy: none
		sourceColumn: price

		annotation SummarizationSetBy = User

	column currency
		dataType: string
		lineageTag: d31d01bb-7dc1-4b74-a29d-3ad8b34ddf93
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column deactivation_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 846c2ea9-84cf-4cb0-83b3-c23835a8c266
		summarizeBy: none
		sourceColumn: deactivation_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column deactivation_reason
		dataType: string
		lineageTag: 47108dfd-6400-47c6-8d55-700ee9a5fe2b
		summarizeBy: none
		sourceColumn: deactivation_reason

		annotation SummarizationSetBy = Automatic

	column operation_type_id
		dataType: int64
		formatString: 0
		lineageTag: 702b726f-7348-492d-92f6-8b0ff5b9553f
		summarizeBy: none
		sourceColumn: operation_type_id

		annotation SummarizationSetBy = Automatic

	partition fac_listings = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(
				        File.Contents("C:\Users\luisa\OneDrive\Escritorio\real_state_analysis\real_state_source.xlsx"),
				        null,
				        true
				    ),
				    fac_listings_Sheet = Source{[Item="fac_listings", Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(fac_listings_Sheet, [PromoteAllScalars=true]),
				    #"Removed Other Columns" =
				        Table.SelectColumns(
				            #"Promoted Headers",
				            {
				                "listing_id",
				                "property_id",
				                "operation_type_id",
				                "publication_date",
				                "deactivation_date",
				                "price",
				                "currency",
				                "deactivation_reason"
				            }
				        ),
				    #"Changed Type" =
				        Table.TransformColumnTypes(
				            #"Removed Other Columns",
				            {
				                {"listing_id", Int64.Type},
				                {"property_id", Int64.Type},
				                {"operation_type_id", Int64.Type},
				                {"publication_date", type date},
				                {"deactivation_date", type date},
				                {"price", Int64.Type},
				                {"currency", type text},
				                {"deactivation_reason", type text}
				            },
				            "es-AR"
				        )
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

